CREATE TABLE IF NOT EXISTS `organisateur` (
  `nom` varchar(100) NOT NULL DEFAULT '',
  `prenom` varchar(100) NOT NULL DEFAULT '',
  `login` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  CONSTRAINT PK_ORGANISATEUR PRIMARY KEY(`nom`,`prenom`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `equipe` (
  `nomEq` varchar(100) NOT NULL DEFAULT '',
  `niveauEq` numeric(1) CHECK (niveauEq BETWEEN 1 AND 5),
  `nomClub` VARCHAR(100),
  CONSTRAINT PK_NOMEQUIPE PRIMARY KEY (`nomEq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `joueur`(
  `nomJ` varchar(100) NOT NULL DEFAULT '',
  `prenomJ` varchar(100) NOT NULL DEFAULT '',
  `niveauJ` VARCHAR(100) CHECK (niveauJ IN ('LOISIR','DEPARTEMENTAL','REGIONAL','ELITE','PRO')),
  `nomEqq` VARCHAR(100) NOT NULL DEFAULT '',
  CONSTRAINT PK_NomPrenomJ PRIMARY KEY (`nomJ`,`prenomJ`),
  CONSTRAINT FK_JNOMEQ FOREIGN KEY(`nomEqq`) REFERENCES `equipe`(`nomEq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `poule` (
	`numPoule` NUMERIC(65) NOT NULL,
	`terrain` VARCHAR(100) NOT NULL DEFAULT '',
	CONSTRAINT PK_NUMPOULE PRIMARY KEY (`numPoule`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `appartient`(
	`nomEq` VARCHAR(100), 
	`numPoule` NUMERIC(65),
	CONSTRAINT Pk_APPARTIENT PRIMARY KEY (`nomEq`,`numPoule`),
	CONSTRAINT FK_ANOMEQ FOREIGN KEY(`nomEq`) REFERENCES `equipe`(`nomEq`),
	CONSTRAINT FK_ANUMPOULE FOREIGN KEY(`numPoule`) REFERENCES `poule`(`numPoule`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

